# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Audio-TagLib-Shell
version:      1.41
version_from: lib/Audio/TagLib/Shell.pm
installdirs:  site
requires:
    Audio::TagLib:                 1.4
    Cwd:                           2.06

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
